package com.campus.client.services.rag;

/**
 * Result of one RAG round-trip: the retrieved context (for transparency,
 * per the design report's "Step 4: Display" requirement) and the grounded
 * answer generated by the LLM.
 */
public class RagResult {

    private final String question;
    private final String context;
    private final String answer;

    public RagResult(String question, String context, String answer) {
        this.question = question;
        this.context = context;
        this.answer = answer;
    }

    public String question() { return question; }
    public String context() { return context; }
    public String answer() { return answer; }
}